<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class MaisonSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // On désactive les clés étrangères pour vider proprement la table
        DB::statement('SET FOREIGN_KEY_CHECKS=0;');
        DB::table('maisons')->delete();
        DB::statement('SET FOREIGN_KEY_CHECKS=1;');

        // Insertion de vos données SQL réelles
        DB::table('maisons')->insert([
            [
                'id' => 1,
                'titre' => 'fjhgjfdgGHJKLjk',
                'description' => 'ghjNBV?khgfdhjk',
                'prix' => 4546877,
                'vues' => 1,
                'est_loue' => 0,
                'adresse' => 'fsaghssfa',
                'image' => 'maisons/principales/wK4ZTajlS8loCDKPlzCl064lrNBEB0ZbpouCxTFS.png',
                'latitude' => 6.1985522,
                'longitude' => 1.1837147,
                'created_at' => '2026-05-11 17:33:55',
                'updated_at' => '2026-05-26 01:53:42',
                'utilisateur_id' => 2,
                'categorie_id' => null, // Était NULL dans vos données
                'ville' => 'anie',
                'visites_demandees' => 0,
            ],
            [
                'id' => 2,
                'titre' => 'fjhgjfdgGHJKLjk',
                'description' => 'jfkdjfhgklfhjggklhg fbehjterhtrejvrntjmb5j5 mj5m5 mu5 k5jb65m 57bm5n67nm65m56666 m5m7m56 m75m56nvb45b',
                'prix' => 655678,
                'vues' => 3,
                'est_loue' => 0,
                'adresse' => 'jfgkhlkcj',
                'image' => 'maisons/principales/DIceqBiTV4PDGO7RIFb1tjjtVW60dlHeBoJdJvPQ.jpg',
                'latitude' => 6.1911776,
                'longitude' => 1.1935023,
                'created_at' => '2026-05-11 17:59:46',
                'updated_at' => '2026-05-28 16:40:29',
                'utilisateur_id' => 2,
                'categorie_id' => 1,
                'ville' => 'yyyyyy',
                'visites_demandees' => 0,
            ],
            [
                'id' => 3,
                'titre' => 'fjhgjfdghfggkjg788',
                'description' => 't687btotbo98o',
                'prix' => 99999,
                'vues' => 5,
                'est_loue' => 0,
                'adresse' => 'ykutdfghlf',
                'image' => 'maisons/principales/fzIo9rFRvMcyqBbDl3Hwxc5QO2OFAwt0nPx1UHNO.webp',
                'latitude' => 6.1995542,
                'longitude' => 1.2017446,
                'created_at' => '2026-05-11 18:00:58',
                'updated_at' => '2026-05-26 01:53:12',
                'utilisateur_id' => 2,
                'categorie_id' => 3,
                'ville' => 'ouiou',
                'visites_demandees' => 1,
            ],
            [
                'id' => 4,
                'titre' => 'yterbtrwveq',
                'description' => 'uuuuutbhryjmiytrbv4',
                'prix' => 53455,
                'vues' => 5,
                'est_loue' => 0,
                'adresse' => 'bhgdf s',
                'image' => 'maisons/principales/WVKGtQohj7IiUNQXr8ZRYAg4GZ5xaLVMpnLIHxCX.webp',
                'latitude' => 6.2163260,
                'longitude' => 1.2055223,
                'created_at' => '2026-05-12 00:45:40',
                'updated_at' => '2026-05-28 16:47:47',
                'utilisateur_id' => 2,
                'categorie_id' => 2,
                'ville' => 'cvnbnc',
                'visites_demandees' => 0,
            ],
            [
                'id' => 5,
                'titre' => 'thjynrbever v',
                'description' => 'trhmtyjmn rtb ev',
                'prix' => 45344,
                'vues' => 10,
                'est_loue' => 0,
                'adresse' => 'ghjgk',
                'image' => 'maisons/principales/Hn7XWI7Uegqw1FYfy1qVrciBi92oYPgVdbWlJzEA.webp',
                'latitude' => 6.1985877,
                'longitude' => 1.2031183,
                'created_at' => '2026-05-12 00:46:28',
                'updated_at' => '2026-05-26 11:07:03',
                'utilisateur_id' => 2,
                'categorie_id' => 3,
                'ville' => 'oiu0up',
                'visites_demandees' => 2,
            ],
            [
                'id' => 8,
                'titre' => 'rrrrrrrrrrr',
                'description' => 'rrrrrrrrrrrrr',
                'prix' => 9909909,
                'vues' => 5,
                'est_loue' => 0,
                'adresse' => 'legbassito',
                'image' => 'maisons/principales/uZerMXagIJSnNqlB47Q3VVd7BefwLsamf2Vl9Y12.webp',
                'latitude' => 6.2020913,
                'longitude' => 1.2024314,
                'created_at' => '2026-05-12 03:06:16',
                'updated_at' => '2026-05-26 14:39:58',
                'utilisateur_id' => 2,
                'categorie_id' => 1,
                'ville' => 'LOME',
                'visites_demandees' => 0,
            ],
            [
                'id' => 9,
                'titre' => 'fdgbdfbdf',
                'description' => 'db dsfbs',
                'prix' => 3452534,
                'vues' => 12,
                'est_loue' => 1,
                'adresse' => 'AKPAME',
                'image' => 'maisons/principales/UYYAv8ZE7ykJi8kEPTXVudQN1JblgfR0dyU7DlEw.jpg',
                'latitude' => 6.2205000,
                'longitude' => 1.1975956,
                'created_at' => '2026-05-12 04:05:35',
                'updated_at' => '2026-05-29 10:47:20',
                'utilisateur_id' => 2,
                'categorie_id' => 2,
                'ville' => 'SOKODE3',
                'visites_demandees' => 0,
            ],
            [
                'id' => 11,
                'titre' => 'HGFKHJGLHJKER jhfjfjh jhfjhf jgfkj dkhgkjh gfk jhv',
                'description' => 'DKFJOIUTIUHGILUWAGW',
                'prix' => 1111175,
                'vues' => 8,
                'est_loue' => 1,
                'adresse' => 'agoe',
                'image' => 'maisons/principales/rfKajJhlErcHpHlxa9DF43iTHnigISpPbm84DZ7y.png',
                'latitude' => 6.2062985,
                'longitude' => 1.2024314,
                'created_at' => '2026-05-13 19:24:34',
                'updated_at' => '2026-05-26 11:06:53',
                'utilisateur_id' => 2,
                'categorie_id' => 3,
                'ville' => 'ANEHO',
                'visites_demandees' => 5,
            ],
            [
                'id' => 12,
                'titre' => 'HGFKHJGLHJKER FJHFJ HFJ JGHKHJKVKJVLH JKBK',
                'description' => 'DKFJOIUTIUHGILUWAGW',
                'prix' => 6666666,
                'vues' => 33,
                'est_loue' => 0,
                'adresse' => 'agoe',
                'image' => 'maisons/principales/T3gd5TJOoXe2Y4RlUToTTMfgxJaxe2YR0EKtcaUJ.png',
                'latitude' => 6.1923123,
                'longitude' => 1.1981386,
                'created_at' => '2026-05-13 19:26:27',
                'updated_at' => '2026-05-26 11:08:20',
                'utilisateur_id' => 2,
                'categorie_id' => 3,
                'ville' => 'ANEHO',
                'visites_demandees' => 12,
            ],
            [
                'id' => 13,
                'titre' => 'Deux Chambres Salon WC Douche Interne',
                'description' => 'DKFJOIUTIUHGILUWAGW',
                'prix' => 999999999,
                'vues' => 5,
                'est_loue' => 0,
                'adresse' => 'jfgkhlkcjgvbjlkhjcb mn',
                'image' => 'maisons/principales/ZXfnCm05My2aGENrGIsezo6kPWK28DjhOGRjblNA.png',
                'latitude' => 6.2178966,
                'longitude' => 1.2135928,
                'created_at' => '2026-05-13 19:39:22',
                'updated_at' => '2026-05-24 03:45:33',
                'utilisateur_id' => 2,
                'categorie_id' => 2,
                'ville' => 'yyyyyy',
                'visites_demandees' => 1,
            ],
            [
                'id' => 14,
                'titre' => 'sgsdfasvsaa',
                'description' => 'SDFNGMHG,FGKGFD',
                'prix' => 36433,
                'vues' => 2,
                'est_loue' => 0,
                'adresse' => 'DFDFHJFJFDHD',
                'image' => 'maisons/principales/bMF4StT4gDW8O9B7K2ZyMhllYGCArF7aF7SQ7zQs.webp',
                'latitude' => 6.2148685,
                'longitude' => 1.2005138,
                'created_at' => '2026-05-17 02:01:17',
                'updated_at' => '2026-05-20 14:49:45',
                'utilisateur_id' => 2,
                'categorie_id' => 1,
                'ville' => 'GFFJFJGF',
                'visites_demandees' => 0,
            ],
            [
                'id' => 15,
                'titre' => 'sgsdfasvsaa',
                'description' => 'SDFNGMHG,FGKGFD',
                'prix' => 90000,
                'vues' => 3,
                'est_loue' => 1,
                'adresse' => 'Agoe',
                'image' => 'maisons/principales/XRljhCbScKne81cy8rypbnsXUmBfFXMmBa6obMpi.webp',
                'latitude' => 6.2123087,
                'longitude' => 1.2025738,
                'created_at' => '2026-05-20 14:03:52',
                'updated_at' => '2026-05-26 11:36:23',
                'utilisateur_id' => 2,
                'categorie_id' => 1,
                'ville' => 'LOME',
                'visites_demandees' => 0,
            ],
            [
                'id' => 16,
                'titre' => 'villa',
                'description' => 'SDFNGMHG,qwfrwerqc',
                'prix' => 90000,
                'vues' => 0,
                'est_loue' => 0,
                'adresse' => 'Agoe',
                'image' => 'maisons/principales/vqjMTl8wGbZCuQ37aSoDPccclROqfR91aGOZXoiB.webp',
                'latitude' => 6.1913179,
                'longitude' => 1.1999989,
                'created_at' => '2026-05-26 13:15:36',
                'updated_at' => '2026-05-26 13:15:36',
                'utilisateur_id' => 2,
                'categorie_id' => 1,
                'ville' => 'LOME',
                'visites_demandees' => 0,
            ],
            [
                'id' => 17,
                'titre' => 'Appartement',
                'description' => 'SDFNGMHG,qwfrwerqc',
                'prix' => 676576,
                'vues' => 0,
                'est_loue' => 0,
                'adresse' => 'zangera',
                'image' => 'maisons/principales/W5Vv0LpjqEHZaPdbHcW762RA0hoDwWpuAVjHBBUt.webp',
                'latitude' => 6.2208413,
                'longitude' => 1.1941624,
                'created_at' => '2026-05-26 13:22:49',
                'updated_at' => '2026-05-26 13:22:49',
                'utilisateur_id' => 2,
                'categorie_id' => 2,
                'ville' => 'LOME',
                'visites_demandees' => 0,
            ],
            [
                'id' => 18,
                'titre' => 'Appartement',
                'description' => 'SDjgkcvhhbilhnlokjm;okhnjlhohklj',
                'prix' => 909090,
                'vues' => 1,
                'est_loue' => 0,
                'adresse' => 'LOMNAVA',
                'image' => 'maisons/principales/4lGXBioJOOHGETBAqvHqFGi8GwWn3Ss5o1oHL7UO.webp',
                'latitude' => 6.2053119,
                'longitude' => 1.2132168,
                'created_at' => '2026-05-26 13:23:48',
                'updated_at' => '2026-05-26 13:26:54',
                'utilisateur_id' => 2,
                'categorie_id' => 1,
                'ville' => 'ATAKPAME',
                'visites_demandees' => 0,
            ],
            [
                'id' => 19,
                'titre' => 'HGKJHGKJH',
                'description' => 'HGKBGNIJHLK;okhnjlhohklj',
                'prix' => 666666,
                'vues' => 0,
                'est_loue' => 0,
                'adresse' => 'JHGKJ',
                'image' => 'maisons/principales/Efc4UFuTtXzTJ3mKdsFkb445grLMaWFRlVP7LGpk.webp',
                'latitude' => 6.1795423,
                'longitude' => 1.2054920,
                'created_at' => '2026-05-26 13:24:47',
                'updated_at' => '2026-05-26 13:24:47',
                'utilisateur_id' => 2,
                'categorie_id' => 2,
                'ville' => 'AKARE',
                'visites_demandees' => 0,
            ],
            [
                'id' => 20,
                'titre' => 'QUATREChambres Salon WC Douche Interne',
                'description' => 'TYOVYBOIGUO UIGO IUIGIGUICVITCIUY HH GYUF HO OH YF HVLHKU TD UKTH LHV',
                'prix' => 1000000,
                'vues' => 0,
                'est_loue' => 0,
                'adresse' => 'JJJJJJ',
                'image' => 'maisons/principales/1jdVqppK0sGUPUctFsS7jtMPFUXoNdyhO52rwF90.webp',
                'latitude' => 6.1909766,
                'longitude' => 1.1977673,
                'created_at' => '2026-05-26 13:26:31',
                'updated_at' => '2026-05-26 13:26:31',
                'utilisateur_id' => 2,
                'categorie_id' => 1,
                'ville' => 'KARA',
                'visites_demandees' => 0,
            ],
        ]);
    }
}